### ISSUE TITLE
GIVE KREATIVEKORP TO SOMEONE ELSE MAYBE THE OWNER OF RIGLOS

### ISSUE THREAD

**Issue by ghost** [RebeccaRGB/romtool#16]
You are not even presenting what the competing fonts are on your website so you're manipulating its users you don't deserve to own ANY of Kreative Korp.

**Comment by Fuck-Kreative-Korp** [comment]
GIVE KREATIVEKORP TO SOMEONE ELSE MAYBE THE OWNER OF RIGLOS

**Comment by Fuck-Kreative-Korp** [comment]
YOU ARE TRYING TO MURDER ME, FFUUCCKK  YYOOUU

**Comment by Fuck-Kreative-Korp** [comment]
FUCK KREATIVE KORP

**Comment by Fuck-Kreative-Korp** [comment]
YOU DON'T DESERVE TO OWN ANYTHING NOT A FONT DEVELOPMENT MACHINE NOT EVEN A SINGLE PENNY

**Comment by Fuck-Kreative-Korp** [comment]
FUCK YOU ISISOQKWHHDIDJAOSJJWNWIWODOIFURUEJIAKDJDKJD YOU'RE NAZI AND NIGGER

**Comment by Diwjhwgwnwjjqjwjwkiekthbshwjkowngdfghds** [comment]
UNCLOSE

**Comment by Diwjhwgwnwjjqjwjwkiekthbshwjkowngdfghds** [comment]
NOW

**Comment by Diwjhwgwnwjjqjwjwkiekthbshwjkowngdfghds** [comment]
UUNNCCLLOOSSEE NAAAJQHHDJDIDJKSKKW

**Comment by Diwjhwgwnwjjqjwjwkiekthbshwjkowngdfghds** [comment]
UNCLOSE BECAUSE YOU HAVEN'T GIVEN THE WEBSITE
