### ISSUE TITLE
THERE IS  NO SUCH THING AS BLUE DACTED

### ISSUE THREAD

**Issue by Diwjhwgwnwjjqjwjwkiekthbshwjkowngdfghds** [RebeccaRGB/romtool#20]
YOU MADE IT UP  LIKE I MADE UP BLUEMAILING WHICH IS SAYING AN AWFUL QUOTE

**Comment by RebeccaRGB** [comment]
No, you said bluemailing was deleting comments. Idiot.

**Comment by Diwjhwgwnwjjqjwjwkiekthbshwjkowngdfghds** [comment]
FUCK OFF NIVGGGGET

**Comment by Fuck-Kreative-Korp-Kdhabhsjsjj** [comment]
JUST DON'T BLUEMAIL MY ISSUES
