### ISSUE TITLE
You are banned

### ISSUE THREAD

**Issue by Fuck-Kreative-Korp-Kdhabhsjsjj** [RebeccaRGB/romtool#27]
You are banned from owning Kreative fonts.

**Comment by RebeccaRGB** [comment]
You have no authority there.

**Comment by Fuck-Kreative-Korp-Kdhabhsjsjj** [comment]
Authority does not ever matter

**Comment by Fuck-Kreative-Korp-Kdhabhsjsjj** [comment]
I don't want authority because it does NOT matter!
